variable subnetgroup {}
variable allocated_storage {}
variable engine {}           
variable engine_version {}        
variable instance_class {}      
variable multi_az {}             
variable name {}             
variable username {}  
variable password {}                
variable port {}                
variable publicly_accessible {}
variable storage_encrypted {}  
variable storage_type {} 
variable cidr_block_private_subnet1 {}    
variable cidr_block_private_subnet2 {}
variable vpc_security_group_ids {}
variable vpc_id {}
variable prefix {}